version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - YOUTUBE_API_KEY=${YOUTUBE_API_KEY}
      - SECRET_KEY=${SECRET_KEY}
      - FLASK_ENV=production
    volumes:
      # Mount folders untuk persistent storage
      - ./data:/app/data
      - ./analyses:/app/analyses
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
